name: website-examiner

services:
  postgres:
    image: postgres:18
    container_name: webex_postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webex_db
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8.4
    container_name: webex_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
